name: MenuPlugin
version: ${project.version}
main: fr.art333.menuplugin.MenuPlugin
api-version: 1.16
authors: [ Art333 ]
description: Plugin use to get menus with by example a compass
commands:
  menu:
    description: Open server menu
    usage: /<command>